export const Types = {
  COMMUNICATION_OUTBOUND: "communication_outbound",
  GROUP_CELEBRATE: "group_celebrate",
  GROUP_CLINIC: "group_clinic",
  GROUP_COUNSEL: "group_counsel",
  GROUP_FRIENDSHIP: "group_friendship",
  GROUP_SUPPORT: "group_support",
  INDIVIDUAL_MAN_DEVICE: "individual_man_device",
  INDIVIDUAL_MAN_FINANCE: "individual_man_finance",
  INDIVIDUAL_MAN_STRENGTH: "individual_man_strength",
  INDIVIDUAL_NONBINARY_CELEBRATE: "individual_nonbinary_celebrate",
  INDIVIDUAL_NONBINARY_DATETIME: "individual_nonbinary_datetime",
  INDIVIDUAL_NONBINARY_HEALTHWORKER_QUIT_AIDS:
    "individual_nonbinary_healthworker_quit_aids",
  INDIVIDUAL_WOMAN_DATETIME: "individual_woman_datetime",
  INDIVIDUAL_WOMAN_HEALTHWORKER_QUIT_AIDS:
    "individual_woman_healthworker_quit_aids",
  INTROSPECTIVE_JOURNAL: "introspective_journal",
  INTROSPECTIVE_TIME: "introspective_time",
  MILESTONE_LUNG_RECOVERY: "milestone_lung_recovery",
  MILESTONE_POST_QUIT_DAY_1: "milestone_post_quit_day_1",
  MILESTONE_POST_QUIT_DAY_2: "milestone_post_quit_day_2",
  MILESTONE_POST_QUIT_DAY_3: "milestone_post_quit_day_3",
  MILESTONE_POST_QUIT_DAY_4: "milestone_post_quit_day_4",
  MILESTONE_POST_QUIT_DAY_5: "milestone_post_quit_day_5",
  MILESTONE_POST_QUIT_DAY_6: "milestone_post_quit_day_6",
  MILESTONE_POST_QUIT_WEEK_1: "milestone_post_quit_week_1",
  MILESTONE_POST_QUIT_WEEK_2: "milestone_post_quit_week_2",
  MILESTONE_POST_QUIT_WEEK_3: "milestone_post_quit_week_3",
  MILESTONE_RIBBON: "milestone_ribbon",
  MILESTONE_TROPHY: "milestone_trophy"
};
